### ISSUE TITLE
macOS build missing file extension, preventing launch

### ISSUE THREAD

**Issue by michaelcooke** [unitystation/stationhub#104]
The application in the [Unitystation .dmg](https://unitystationfile.b-cdn.net/HubSetup.dmg) is missing the `.app` file extension and will open as a directory instead of launching as an application when opened.
![Screen Shot 2021-07-28 at 12 20 06 AM](https://user-images.githubusercontent.com/12518009/127263835-bf3bc119-a97f-4187-ab38-9cd1e85cec01.png)

I'm willing to work on this and submit a PR if somebody can point me in the right direction. I'm also willing to test a fix offered somewhere else.

**Comment by corp-0** [comment]
is the the game executable or the launcher executable what is missing the extension?

**Comment by corp-0** [comment]
related https://docs.avaloniaui.net/docs/distribution-publishing/macos

**Comment by corp-0** [comment]
closing in favor or #119
