### ISSUE TITLE
When a download has finished, play button says "CANCEL" instead of "PLAY"

### ISSUE THREAD

**Issue by corp-0** [unitystation/stationhub#107]
## environment
version: 927/latest develop at the time of writing.
os: Windows 10

## Steps to reproduce
1- Download an installation from a server
2- See how the button should say "PLAY" when it finishes, but says "CANCEL" instead.

**Comment by RedlineTriad** [comment]
Works on Linux, probably a Windows issue.

**Comment by corp-0** [comment]
Works on MacOS Catalina, so confirmed Windows-only issue

**Comment by corp-0** [comment]
after the #117 bug, this doesn't happen anymore. Closing.
