### ISSUE TITLE
Stuck on login screen on first login

### ISSUE THREAD

**Issue by corp-0** [unitystation/stationhub#109]
OS: Windows, although it seems it also occurs in Linux
version: 928, latest version

Steps to reproduce:
- Delete all folders and files, use a fresh version of the application
- fill the inputs with your credentials and click "log in".
- It won't change to the server list view even though it is updating the server list in the background.

**Comment by corp-0** [comment]
might be related to #107 as a windows-only issue. Redline theorized it could be an avalonia bug.

**Comment by corp-0** [comment]
Note that it only fails the first time you do it, subsequent times will properly move you from login view to server list view.

**Comment by corp-0** [comment]
I have tested this on MacOS Catalina 10.15 (VM) and I get the same behaviour as described above.

**Comment by RedlineTriad** [comment]
Works on Linux with the AUR version, though first time login doesn't work.

**Comment by corp-0** [comment]
> first time login doesn't work.

Yeah, subsequent times works for all other platforms as well. So this isn't a windows-only issue for a change.

**Comment by corp-0** [comment]
fixed on #120
