### ISSUE TITLE
user version of the app shows the debug console

### ISSUE THREAD

**Issue by corp-0** [unitystation/stationhub#116]
version: 928 and latest 

Having the debug console is handy for us developers, but it is very ugly for the final users.

To solve this issue, modify our ci workflow to perform two different types of builds, debug and release. Release should overwrite the project configuration like this ``-p:OutputType=WinExe``

**Comment by RedlineTriad** [comment]
We can just always do this, not just during publishing. Just do it in the `.csproj`

**Comment by corp-0** [comment]
the .csproj can handle different values depending on the type of build?

**Comment by RedlineTriad** [comment]
> the .csproj can handle different values depending on the type of build?

We can *always* use win exe, unless you see a reason not to.

**Comment by corp-0** [comment]
it is cool to have for when we test stuff

**Comment by RedlineTriad** [comment]
> it is cool to have for when we test stuff

Don't you still get a console in the IDE or somewhere?

**Comment by corp-0** [comment]
yeah but when we download from the artifacts

**Comment by RedlineTriad** [comment]
> yeah but when we download from the artifacts

You still have log files or you can run it from console.
But sure you can also just do it in publish only.

**Comment by corp-0** [comment]
reopening as tested on latest build from the CI artifacts still shows the debug console
