### ISSUE TITLE
Progress bar lost when downloading and a server list fetch occurs

### ISSUE THREAD

**Issue by corp-0** [unitystation/stationhub#117]
OS: tested on Windows and Mac, missing Linux reproduction
Version: 928, only happens from commit 2d2e6af8f3dd1529c14bc7d496b5021a1e51bdbb onwards.
Introduced after: #102 

Description: The progress bar is lost while downloading and a server list fetch occurs.

Steps:
1. Build and download an installation.
2. Wait until server list is refreshed.
3. Progress bar is lost, button goes back to "Download".

**Comment by RedlineTriad** [comment]
Yeah I know about this, the solution to this is to seperate Downloads into download managers and not do it in `Server` anymore.

**Comment by corp-0** [comment]
``Download.cs`` has code related to downloading and extracting, it threw me off at first why my changes weren't working like that code wasn't ever called and it was in fact never called.

**Comment by RedlineTriad** [comment]
> `Download.cs` has code related to downloading and extracting, it threw me off at first why my changes weren't working like that code wasn't ever called and it was in fact never called.

I was in the middle of refactoring things out of `Server` into `Download` and `Installation` when Doobly patched it together so launcher was usable. So there are multiple things where the refactored version is lying around but not being used yet.
I refactored Installation already but not yet download.
