### ISSUE TITLE
MacOS builds should be bundled in a .app

### ISSUE THREAD

**Issue by corp-0** [unitystation/stationhub#119]
Currently we're building the application as a self-contained app and making Mac users execute it as is, when the proper way to distribute osx apps is to bundle them in a .app container.

Instructions on how to achieve it can be read here:  https://docs.avaloniaui.net/docs/distribution-publishing/macos

Solution:
Modify our CI workflow to include the bundling step for MacOSX and don't build it as self-contained!

**Comment by DeadLineSS13** [comment]
Shit moment
