### ISSUE TITLE
Users can download a server's station files multiple times at once.

### ISSUE THREAD

**Issue by Puppyguarb** [unitystation/stationhub#133]
Description: A user can download the server files multiple times. The progress bar will also reset when switching tabs, or when the server list refreshes. The progress bar's disappearance is merely visual, as the download continues just fine in the console.

This issue occurred on windows 10.

Steps to reproduce:
1. Start downloading a server's station files.
2. Switch to a different tab of the stationhub, then switch back.
3. Start downloading a server's station files again.

Alternatively,
1. Start downloading a server's station files.
2. Click download again when the server list refreshes.

Video showing off the issue: 

https://user-images.githubusercontent.com/88409694/138938914-5e7276b3-c035-4fff-9cc3-59c8a7045f76.mp4

**Comment by RedlineTriad** [comment]
This is already fixed in develop.
