### ISSUE TITLE
Add build instructions 

### ISSUE THREAD

**Issue by jamessimo** [unitystation/stationhub#136]
I am looking to fix and wrap the OSX build but have no idea how to build/compile this. Could we add steps to the readme?

**Comment by RedlineTriad** [comment]
Adding it to the read-me seems reasonable.
Though all that is required is `dotnet build` for building.
And for publishing, copied directly from our pipeline: `dotnet publish --configuration Release --runtime ${{ matrix.target-platform }} --output ~/publish`

**Comment by CorruptComputer** [comment]
A documentation dir was added in #175, so these instructions could either go there in their own file or directly in the readme.

**Comment by corp-0** [comment]
on the readme itself would be the best. Just a 3 steps how to get started. Clone, get dependencies, run/build
