### ISSUE TITLE
Dae Linux patch sh script

### ISSUE THREAD

**Issue by Bod9001** [unitystation/stationhub#141]
[Unitystation-fix.zip](https://github.com/unitystation/stationhub/files/7971894/Unitystation-fix.zip)

idk what to do with this

**Comment by RedlineTriad** [comment]
Without context I am not going to start opening zip files which apparently contain shell scripts.

**Comment by potatoalienof13** [comment]
That doesnt contain a shell script.

**Comment by potatoalienof13** [comment]
Its stationhub.

**Comment by potatoalienof13** [comment]
929, specifically.

**Comment by RedlineTriad** [comment]
I still have literally no clue what issue needs to be solved here.
So unless someone explains I will just close it.
