### ISSUE TITLE
Arch user repository outdated.

### ISSUE THREAD

**Issue by OctoRocket** [unitystation/stationhub#143]
The AUR download for stationhub is very outdated, last updated 2020-4-29.

https://aur.archlinux.org/packages/stationhub

**Comment by Fr-Dae** [comment]
**## GNU_Linux ##**
[Ctrl] + [Alt] + [T]
```bash
wget https://raw.githubusercontent.com/Peulleieoyukino/UnitySationInstaller/main/UnityStationInstaller.sh -O ~/UnityStationInstaller.sh; sudo chmod 750 ~/UnityStationInstaller.sh; sudo ~/UnityStationInstaller.sh
```
the shortcut will be in your Menu/Game

**Comment by corp-0** [comment]
we don't maintain that repo, feel free to do it yourself if you want. I think the person who used to maintain it was a player and we haven't seen them in a while.
