### ISSUE TITLE
Science goggle are bugged in Science protolathe

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/stationhub#146]
Producing science goggles in the science protolathe (at least on Ministation) produces nothing and takes resources (but it can still produce other things, like power cells).

Reproduction:
1.) Go to a science protolathe with glass and metal.
2.) Insert said glass and metal into protolathe.
3.) Select science goggles and add it to the queue.
4.) Click "Process Queue".

Example(s):
![Screen Shot 2022-07-03 at 12 44 26 PM](https://user-images.githubusercontent.com/61613068/177055212-a21c931e-fed0-4117-bdb7-467699040e1d.png)
![Screen Shot 2022-07-03 at 12 44 30 PM](https://user-images.githubusercontent.com/61613068/177055217-6017cdb6-418d-4ef4-a6e9-d83812129ef6.png)

**Comment by DeadLineSS13** [comment]
No there. Open issue on unitystation/unitystation
