### ISSUE TITLE
People can access any vendor anywhere

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/stationhub#147]
To clarify: if someone successes a vendor and then walks away, the "Vendor" tab or "Shuttle Console" tab or whatever will still stick in the top right no matter where you are, and in-turn stacks to the side of any previously accessed items. Trying to dispense anything from a far distance will get rid of the tab and respective UI, but the cluttered bug is still a bit of a headache.

Steps:
1.) Access a vendor/console/autolathe/anything that puts up a drop-down UI in the top right.
2.) Walk away.
3.) See results.

Examples:
![Screen Shot 2022-07-03 at 10 57 37 PM](https://user-images.githubusercontent.com/61613068/177090589-9a4d01ab-3cfe-4ea3-8c96-2b2dd5c40c08.png)
![Screen Shot 2022-07-03 at 10 57 40 PM](https://user-images.githubusercontent.com/61613068/177090596-a6df1945-cd75-4e51-a548-21d303d5cfee.png)
![Screen Shot 2022-07-03 at 10 58 10 PM](https://user-images.githubusercontent.com/61613068/177090603-3aa26e08-6ec3-4748-aab3-33778d67082e.png)

**Comment by DeadLineSS13** [comment]
No there. Open issue on unitystation/unitystation
