### ISSUE TITLE
Shutter not linked to button on Squarestation

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/stationhub#148]
This shutter on R&D on Squarestation is not linked to it's respective button.

Steps:
1.) Go to Squarestation.
2.) Go to R&D.
3.) Hit the right-most button in robotics.
4.) See results.

Examples:
![Screen Shot 2022-07-04 at 11 22 45 AM](https://user-images.githubusercontent.com/61613068/177203909-1245d64d-b012-4f6c-9162-5be4619b2aab.png)
![Screen Shot 2022-07-04 at 11 22 49 AM](https://user-images.githubusercontent.com/61613068/177203919-4d6e21b8-0e0a-4fd9-bcf9-d265b5995ee5.png)

**Comment by DeadLineSS13** [comment]
No there. Open issue on unitystation/unitystation
