### ISSUE TITLE
Disposals pipe missing on Fallstation

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/stationhub#149]
As the title suggests, a pipe in the medical wing of Fallstation does exists, specifically the one in-between the medical foyer and virology.

Steps:
1.) Go to Fallstation.
2.) Dispose of something in the trash bin in virology.
3.) See results in the area in-between virology and the main medical area.

Example:
![Screen Shot 2022-07-04 at 11 32 00 AM](https://user-images.githubusercontent.com/61613068/177204596-fec7e569-cba1-4b6f-8be5-e30366a30ced.png)

**Comment by DeadLineSS13** [comment]
No there. Open issue on unitystation/unitystation
