### ISSUE TITLE
Shutters on Fallstation not connected (Cargo)

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/stationhub#152]
The bottom shutters to the cargo shuttle are not connected to any button at round start.

Steps:
1.) Go to Cargo on fallstation.
2.) Hit the button for the cargo shuttle blast doors.
3.) See results.

Example(s):
![Screen Shot 2022-07-04 at 4 43 01 PM](https://user-images.githubusercontent.com/61613068/177226010-674574e0-46fe-43fe-990b-414835c0f7a0.png)
![Screen Shot 2022-07-04 at 4 43 07 PM](https://user-images.githubusercontent.com/61613068/177226016-a0eb71aa-5396-4a20-a2d5-2f49ebbcc1b9.png)

**Comment by DeadLineSS13** [comment]
No there. Open issue on unitystation/unitystation
