### ISSUE TITLE
Position on shuttles permanently stuck at 100, 100

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/stationhub#154]
When you open a shuttle console, the coordinates shown on the X and Y axis (on the shuttle console UI only, alt-clicking still works) show only 100, 100. These values do not change even if you move or update the console.

Steps:
1.) Go to shuttle.
2.) Fly the shuttle anywhere.
3.) Check the given X and Y values on the console UI.

Example(s):
![Screen Shot 2022-07-09 at 11 10 33 AM](https://user-images.githubusercontent.com/61613068/178118030-80f1a51d-84d7-4ee2-9b3b-9f052b2f8ab0.png)
![Screen Shot 2022-07-09 at 11 13 21 AM](https://user-images.githubusercontent.com/61613068/178118031-5db262b0-dce9-4c7a-9300-62788928d308.png)

**Comment by DeadLineSS13** [comment]
No there. Open issue on unitystation/unitystation
