### ISSUE TITLE
Windows can be moved and can't be welded/wrenched/etc.

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/stationhub#155]
The windows/reinforced windows (the sliver ones, not the blocks) found so common among the stations are not attached to the ground, and can be pushed freely, leading to some frustrating designs and renders a lot of the station's use of windows useless.

Steps:
1.) Go to any station with a window(s) .
2.) Push said window(s).

Example(s):
![Screen Shot 2022-07-09 at 8 09 12 PM](https://user-images.githubusercontent.com/61613068/178129969-00bce8c3-77c3-4b3d-b9da-cf26babd15d0.png)
![Screen Shot 2022-07-09 at 8 09 14 PM](https://user-images.githubusercontent.com/61613068/178129971-d955b7fd-fbfb-4bd4-94a5-d88f78f9ca55.png)

**Comment by DeadLineSS13** [comment]
No there. Open issue on unitystation/unitystation
