### ISSUE TITLE
Domains in the IP field of a hub listing cause the app to silently drop the entire server list.

### ISSUE THREAD

**Issue by craftxbox** [unitystation/stationhub#161]
If *any* of the entries in the serverlist endpoint contain data in the IP field that does *not* resolve to an IP address (either v4 or v6, both work), Stationhub will report no error yet display no servers in the server list

**Comment by CorruptComputer** [comment]
Is this still a problem? I just tested it locally, replacing what is returned from the API with a domain:
![image](https://user-images.githubusercontent.com/5573038/223015193-b4965f17-b0f5-4508-bfca-0f484ad56d25.png)

**Comment by craftxbox** [comment]
Weirdly not with direct entry. I just poked a fake listing into the database to the same effect: 
![image](https://user-images.githubusercontent.com/7443752/223016083-2c36f4de-610b-4ea7-a31e-d3dce4a615f7.png)
Im going to do some more poking as this definitely WAS an issue when I was testing unitystation/unitystation#9205

**Comment by craftxbox** [comment]
![]( https://transfur.science/hsudqqev ) This image was taken the day I was testing. Aug-30-2022

**Comment by corp-0** [comment]
What happns if you use an invalid IP/domain? Does it break the entire server list?

**Comment by craftxbox** [comment]
I'm unable to replicate the problem with domains, Any invalid IP or domain material simply causes an error with the ping feature but otherwise loads fine and transparently to the end user. I have only been able to replicate the 'No servers found' issue with the values `::` and `0.0.0.0`. Domains work fine, Regular IPV6 addresses work fine

**Comment by CorruptComputer** [comment]
Ah alright, I'll try it with those, its probably an exception being thrown when trying to ping thats breaking it.

**Comment by CorruptComputer** [comment]
Yeah, found whats happening with that:
```
ArgumentException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address. (Parameter 'address')
```

Should be fixed in my next PR. As for using domain names, do the servers have a domain that I can manually fill in locally to see if it lets me join using that?

**Comment by corp-0** [comment]
not at the moment but they could later when I rework the server list api

**Comment by craftxbox** [comment]
> Yeah, found whats happening with that:
> 
> ```
> ArgumentException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address. (Parameter 'address')
> ```
> 
> Should be fixed in my next PR. As for using domain names, do the servers have a domain that I can manually fill in locally to see if it lets me join using that?

Wild frontier is reachable at `natsuko.ninja`

**Comment by CorruptComputer** [comment]
Ah alright, thanks! I'll test that later today when I make those changes requested in that PR.

**Comment by CorruptComputer** [comment]
Was able to join Wild Frontier FFA using `natsuko.ninja` as the IP address for it with the changes in #185
