### ISSUE TITLE
Remove the login feature from Stationhub

### ISSUE THREAD

**Issue by corp-0** [unitystation/stationhub#165]
As a launcher, it shouldn't also handle login as that depends on the game itself. 

A future fork could be hosting their own solution for authentication, as some will need to, since our authentication system also handles character creation and persistence and they might have their own customisations.

Login and account creation should only be handled by the game itself and a website that communicates with the particular API the game build is using.

**Comment by CorruptComputer** [comment]
I haven't tested it, but does the game handle login if no auth token is provided already?

**Comment by corp-0** [comment]
yeah. It has login in the game itself.
