### ISSUE TITLE
Changelog view should instead show our own curated changelog

### ISSUE THREAD

**Issue by corp-0** [unitystation/stationhub#178]
Currently, the changelog view displays all merged PRs, which a lot of the time isn't really relevant for players. It should instead list the changes we have curated and manually recorded in our changelog api, currently living on https://changelog.unitystation.org/whats-new (for only latest build) or https://changelog.unitystation.org/all-changes

**Comment by CorruptComputer** [comment]
I can include this in my next PR if you want to add it to the 931 release. This change seems like it should be fairly simple.

**Comment by corp-0** [comment]
awesome. I added the issue to the 931 project
