### ISSUE TITLE
Study the possibility of displaying our blog posts on the News view

### ISSUE THREAD

**Issue by corp-0** [unitystation/stationhub#179]
News tab currently displays the changelog to the left and a big static picture on the right.

Investigate the possibility of displaying instead information coming fom our blog API, currently living on:
https://changelog.unitystation.org/posts

There are many appraoches to this task: 
* It could simply show the ``socials_image`` and ``summary`` field of the post object, linking to the blog post on the website to read more about it.
* It could try to render the html content from the post object.
* If needed and estimated easier to do, I could add a new property to the post model with the content converted to markdown.

**Comment by CorruptComputer** [comment]
Could this API be updated to include a link to the blog post as well? I think implementing the summary, image, and link should be fairly straightforward with what is there already. Rendering the content of it might be a bit of a challenge, not sure of the best way to handle that.

**Comment by CorruptComputer** [comment]
Having pagination on this endpoint might be useful as well, similar to how the changelog endpoint works with: 
https://changelog.unitystation.org/all-changes?limit=10

I think something like the most recent 5 posts would probably be good to keep the client from needing to load too much.

**Comment by corp-0** [comment]
> include a link to the blog post as well?

https://unitystation.org/blog/{slug}

> Having pagination on this endpoint might be useful

it is paginated by 10 elements each page. It just doesn't have the offset pagination like the changes endpoint

**Comment by CorruptComputer** [comment]
Ah sounds good then, this seems like a good candidate to add to the 932 release I think. At least to get the summary, image, and link there. If you think these posts need to be rendered in the launcher I would lean on that being a separate feature to be added.

For the 931 release I can hard-code something into that news carousel if you want, just so we have *something* there for now.

**Comment by corp-0** [comment]
sounds like a good compromise. Maybe a simple "Comming soon"
