### ISSUE TITLE
Custom installation directory

### ISSUE THREAD

**Issue by RedlineTriad** [unitystation/stationhub#5]
There should be an option to change the default directory of the installation.

**Comment by corp-0** [comment]
by installation you mean the game installations or hub installation?

**Comment by RedlineTriad** [comment]
> by installation you mean the game installations or hub installation?

Game installations, similar to how you can have a separate Steam library on another disk.

**Comment by CorruptComputer** [comment]
By default I think the games config/installation directory should go to the current users home directory, with a preferences option to change the installation directory. Leaving the config and log dirs there should be fine.

![image](https://user-images.githubusercontent.com/5573038/223176528-5b23c565-7a88-4c97-84f9-a735cccf1604.png)

On Linux and MacOS this is already the case, with the path going to `~/.local/share/StationHub`

On Windows it should probably go to `%APPDATA%\StationHub`, but currently it just goes into the directory StationHub is launched from: https://github.com/unitystation/stationhub/blob/develop/UnitystationLauncher/Models/ConfigFile/Config.cs#L39

**Comment by corp-0** [comment]
that would also make updating hub easier on the users, since they have to delete/replace everything in the Hub directory when updating now.
